### ISSUE TITLE
infogrfia-sistemas numéricos

### ISSUE THREAD

**Issue by Anais-droid** [SistemasTecTlaxiaco/infografia-Anais-droid#2]
[sistemas binarios .pdf](https://github.com/SistemasTecTlaxiaco/infografia-Anais-droid/files/12501811/sistemas.binarios.pdf)

**Comment by elisa1223** [comment]
Redacción 8%
Expresión de ideas  13%
Organización de la información 13%
Uso de imágenes 13%
Presentación visual 13%
Referencias13%
Presentación 13%
Calificación 17/20
Evaluado por Elisa Sánchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
